services:
  postgres:
    image: postgres:16-alpine
    container_name: courseflow-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: alumnos_db
      POSTGRES_USER: ${DB_USERNAME:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin123*}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
